version: "3.8"

services:
  app:
    build: 
      context: .
    volumes:
      - .:/blockcite
    env_file: 
      - docker-compose.env
    depends_on: 
      - db
  db: 
    image: mongo:4.1.8-xenial 
    ports: 
      - 27017:27017